# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mess_likes',
            field=models.ManyToManyField(blank=True, related_name='mes_likes', to='login_app_the_wall.User'),
        ),
    ]
