# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-31 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_auto_20190730_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mess_likes',
            field=models.ManyToManyField(blank=True, related_name='mess_likes', to='login_app_the_wall.User'),
        ),
    ]
